name: QuickUtils
main: com.mrzzj.quickutils.Main
version: 1.0-SNAPSHOT
api-version: 1.16
author: MRZZJ
commands:
  quickutils:
    description: 打开原版GUI界面
    usage: /quickutils <类型>
    aliases: [qu]

permissions:
  quickutils.gui.workbench:
    description: 允许使用虚拟工作台
    default: false
  quickutils.gui.enderchest:
    description: 允许使用末影箱
    default: false
  quickutils.gui.enchant:
    description: 允许使用附魔台
    default: false
  quickutils.admin:
    description: 所有插件权限
    default: false
    children:
      quickutils.gui.workbench: true
      quickutils.gui.enderchest: true
      quickutils.gui.enchant: true
  quickutils.*:
    description: 通配所有功能权限
    default: false
    children:
      quickutils.gui.workbench: true
      quickutils.gui.enderchest: true
      quickutils.gui.enchant: true
