name: QuickUtils
main: com.mrzzj.quickutils.Main
version: 1.4.1
api-version: 1.16
author: MRZZJ
commands:
  quickutils:
    description: 打开原版GUI界面
    usage: /quickutils <类型>
    aliases: [qu]

permissions:
  quickutils.gui.workbench:
    description: 允许使用虚拟工作台
    default: false
  quickutils.gui.enderchest:
    description: 允许使用个人末影箱
    default: false
  quickutils.gui.enchant:
    description: 允许使用附魔界面
    default: false
  quickutils.gui.anvil:
    description: 允许使用铁砧界面
    default: false
  quickutils.gui.grindstone:
    description: 允许使用砂轮界面
    default: false
  quickutils.gui.loom:
    description: 允许使用织布机界面
    default: false
  quickutils.gui.cartography_table:
    description: 允许使用制图台界面
    default: false
  quickutils.gui.smithing:
    description: 允许使用锻造台
    default: false
  quickutils.admin:
    description: 所有插件权限
    default: false
    children:
      quickutils.gui.workbench: true
      quickutils.gui.enderchest: true
      quickutils.gui.enchant: true
      quickutils.gui.anvil: true  
      quickutils.gui.grindstone: true
      quickutils.gui.loom: true
      quickutils.gui.cartography_table: true
  quickutils.*:
    description: 通配所有功能权限
    default: false
    children:
      quickutils.gui.workbench: true
      quickutils.gui.enderchest: true
      quickutils.gui.enchant: true
      quickutils.gui.anvil: true
      quickutils.gui.grindstone: true
